channels:
  - defaults
dependencies:
  - bzip2==1.0.8
  - ca-certificates==2022.07.19
  - certifi==2022.6.15
  - pip==22.1.2
  - pyparsing==3.0.9
  - python==3.10.4
  - pyyaml==6.0
  - git==2.34.1
  - libffi==3.4.2
  - openssl==1.1.1q
  - sqlite==3.39.2
  - tk==8.6.12
  - tzdata==2022a
  - vc==14.2
  - vs2015_runtime==14.27.29016
  - wincertstore==0.2
  - xz==5.2.5
  - zlib==1.2.12
  - pip:
    - asyncio==3.4.3
    - charset-normalizer==2.1.1
    - colorama==0.4.5
    - filelock==3.8.0
    - huggingface-hub==0.9.1
    - idna==3.3
    - packaging==21.3
    - requests==2.28.1
    - setuptools==63.4.1
    - tqdm==4.64.0
    - typing-extensions==4.3.00
    - urllib3==1.26.12
    - wheel==0.37.1

